# Generated by Django 5.1.4 on 2025-05-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving', to='users.usercard')),
            ],
        ),
    ]
