# Generated by Django 5.1.4 on 2025-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingMoney',
        ),
    ]
